### ISSUE TITLE
Xamarin Treeview Project

### ISSUE THREAD

**Issue by tayfunuyar** [MelbourneDeveloper/XamarinFormsChatUI#1]
Can you help me for Treeview in the xamarin project.
Have you got example xamarin treeview? 
Kind Regards...

**Comment by MelbourneDeveloper** [comment]
@tayfunuyar 

Actually, yes, I created a TreeView for Xamarin.Forms. Is what what you mean?

**Comment by MelbourneDeveloper** [comment]
@tayfunuyar 
https://github.com/AdaptSolutions/Xamarin.Forms-TreeView
